# Generated by Django 3.0.2 on 2020-02-07 14:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to=core.models.user_avatar_path),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
