# Generated by Django 3.0.2 on 2020-02-07 16:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200207_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_avatar_path),
        ),
    ]
