# Generated by Django 3.0.2 on 2020-02-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200224_2342'),
        ('user', '0003_auto_20200207_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='users', to='forum.Tag'),
        ),
    ]
